### ISSUE TITLE
sbg-related code in cwl file

### ISSUE THREAD

**Issue by m-gall** [rabix/composer#192]
Hi. Is there any way of exporting the cwl files from composer minus the sbg code? Thanks.

**Comment by mayacoda** [comment]
Hey @m-gall!

We currently don't provide that option, but it does seem extremely useful! I'll create a task in our internal backlog.

For cwl v1.0 tools and workflows, all SBG fields in the CWL are purely metadata, for example (almost) everything you enter in the App Info tab. For sbg:draft-2 apps, some of this code is required for execution, so we won't be able to remove it without affecting how the app runs.

If you are describing a tool or workflow and saving it to one of the SBG platforms, our backend will slap its own SBG metadata fields on the CWL, such as revisions, authorship, createdOn and modifiedOn.
