### ISSUE TITLE
export as svg

### ISSUE THREAD

**Issue by m-gall** [rabix/composer#201]
Hi team rabix,
I'd love to share the cwl visuals I am generating using composer my collaborators. Is there any functionality to export as an svg from composer yet?
Thanks!

**Comment by mayacoda** [comment]
Hello again @m-gall,

We have an export as svg feature that will be released with v1.0.0-rc.1 in the upcoming week. If you're especially adventurous and eager to try it out before then, you can check out the `release/v1.0.0-rc.1` branch and create a binary yourself following the instructions in the `README.md`.
