### ISSUE TITLE
Cannot connect to Cavatica 

### ISSUE THREAD

**Issue by yuankunzhu** [rabix/composer#221]
`https://igor.sbgenomics.com` and `https://cgc.sbgenomics.com` is working, but not `https://cavatica.sbgenomics.com`, can this be fixed?

**Comment by mayacoda** [comment]
@yuankunzhu  which version are you using?

**Comment by yuankunzhu** [comment]
hi @mayacoda, I downloaded from http://rabix.io, I believe it says `Version 1.0.0-beta.3 (1)`

**Comment by mayacoda** [comment]
Sorry about that! The links on the rabix.io homepage will be updated shortly to the new release.

In the meantime, you can download `v1.0.0-rc.1` from our [releases page](https://github.com/rabix/composer/releases/tag/v1.0.0-rc.1). Connecting to Cavatica has been fixed in this version.

**Comment by yuankunzhu** [comment]
Great! Thanks! 

I'm gonna close this issue.
