### ISSUE TITLE
Rabix Composer (1.0.0-rc.1) can't connect to Cavatica

### ISSUE THREAD

**Issue by zhangb1** [rabix/composer#261]
Hey, I tried to use Rabix Composer (1.0.0-rc.1) to connect to cavatica, but failed. 

The error  **Token is not valid for the selected platform. (ESOCKETTIMEDOUT)
Cancel** came out. 

Don't know why the token is not working.

**Comment by sharmatime** [comment]
Hi Bo - 
Were you able to connect previously? Did you try resetting your token on Cavatica and trying again?

**Comment by zhangb1** [comment]
@sharmatime Yes I can connect previously. I tried to regenerate the token and it is not working either.

**Comment by sharmatime** [comment]
Ok, we're looking into it. I'll follow up when I have more info. Thanks for your patience.

**Comment by mattions** [comment]
@zhangb1 this has been addressed in the RC2 https://github.com/rabix/composer/releases/tag/v1.0.0-rc.2

Note that if you are using the RC1, you have to delete the old users, and re-add them selecting the Cavatica platform.

I think this one can be closed now.
