### ISSUE TITLE
can not update output-port name of a command line tool

### ISSUE THREAD

**Issue by rdwrt** [rabix/composer#326]
In 1.0.0-rc.2 when trying to change the output port name of a command line tool it gets overwritten back to "output" after closing and opening the tool

**Comment by TMiguelT** [comment]
I have also noticed this error, meaning you have to edit the raw code for the output name to stick

**Comment by pimpim** [comment]
This seems like a small bug in a basic functionality. Is it resolved in a more recent build?

**Comment by ivanbatic** [comment]
This is fixed on master, probably for some time now. Will be published with 1.0.

**Comment by TMiguelT** [comment]
Thanks. Is the master stable to use, or should I wait until the 1.0 release?
