### ISSUE TITLE
Recursive workflow detector reports a false positive for repeated usage of tools nested inside workflows

### ISSUE THREAD

**Issue by ThomasHickman** [rabix/composer#394]
Example:
test_outer_wf.cwl:
```cwl
class: Workflow
inputs: []
outputs: []
steps:
  - id: inner_wf
    run: test_inner_wf.cwl
    in: []
    out: []
```
test_inner_wf.cwl:
```cwl
class: Workflow
inputs: []
outputs: []
steps:
  - id: step1
    run: test_tool.cwl
    in: []
    out: []
  - id: step2
    run: test_tool.cwl
    in: []
    out: []
```
test_tool.cwl:
```cwl
class: CommandLineTool
inputs: []
outputs: []
```

If you open the outer workflow, it will report the error: `RDF resolution error: Recursive nesting detected for <PATH>/test_tool.cwl`. This is due to https://github.com/rabix/composer/blob/0e1af8fa9e58c83665c1e039e7f06a3619135aa0/electron/src/schema-salad-resolver/schema-salad-resolver.ts#L93
using directly using `traversedExternalPaths` if it's defined and therefore modifying it for instances of the variable higher in the call stack. A solution to this is to use a copy of `traversedExternalPaths` instead of directly using the variable. I'll have a look at submitting a PR and tests for this.

**Comment by kaushik-work** [comment]
@ThomasHickman Thanks for the report and the pull request! We will try to include this in our current round of bug fixes.

**Comment by kaushik-work** [comment]
@ThomasHickman  @marijanlekic 's commit e644f6f3e471067095a7c5303da15e89c23d7b5e addresses this issue.
