### ISSUE TITLE
RDF resolution error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by azat-badretdin** [rabix/composer#397]
Platform: Windows 7.

Multi-level workflows are probable cause of this problem:

I have a directory added to a local workplace that includes a "main" workflow file in which I refer to sub-workflows via relative UNIX-style path.

In this case Rabix Composer constructs a wrong absolute path: it takes installation path for rabix composer and adds specified local path. Expected behavior is the path to the current "main" workflow file plus local path

For example. I have workflow directory "`mydir`" added to Local Files. In that directory I have `wf_main.cwl. `

Under "`mydir`" I have a directory "`mysubdir`" with another workflow: `mysubworkflow.cwl`.

wf_main.cwl refers to that  worflow as:

`run: mysubdir/mysubworkflow.cwl`

I get the message:
`
RDF resolution error: ENOENT: no such file or directory, open 'C:\Users\<username>\rabix-composer\mysubdir\mysubworkflow.cwl'
`

Correct absolute path would be: `<path>\mydir\mysubdir\mysubworkflow.cwl'

**Comment by manabuishii** [comment]
I test on Mac and rabix-composer 1.0.0 .
It works well.


<img width="1307" alt="screen shot 2018-08-16 at 17 24 51" src="https://user-images.githubusercontent.com/7508005/44197425-7f150980-a179-11e8-93bc-b126c2a8b537.png">
<img width="612" alt="screen shot 2018-08-16 at 17 25 49" src="https://user-images.githubusercontent.com/7508005/44197431-83d9bd80-a179-11e8-8110-e2d0bfa0793d.png">

**Comment by whlavina** [comment]
FYI, the issue is observed only on Windows; on Linux/Mac, we don't get the error. I reconfirmed just now that I am seeing this, with Rabix Composer 1.0.0 on Windows 7.

**Comment by marijanlekic** [comment]
Issue is fixed and its pushed to the current master branch, so it can be run/build locally (i do not have any information when will be the next release. I have tried scenario that is given above and it seems its working. Problem was with hardcoded path separators.

**Comment by marijanlekic** [comment]
fixed with:

https://github.com/rabix/composer/commit/ef4b6cbe36252ae23d1af45c4c87d517bfdfdd51
