### ISSUE TITLE
We need feature for following logs.

### ISSUE THREAD

**Issue by kubor** [rabix/composer#419]
Now, the app cannot check logs with follow mode.
Maybe, we want to choice follow/manual refresh mode for logs.

like this.
<img width="169" alt="2018-12-06 15 36 48" src="https://user-images.githubusercontent.com/7918702/49566088-cc0d2d80-f96c-11e8-8e87-b98ca7f5edd2.png">

**Comment by kaushik-work** [comment]
@kubor thanks for the feature request. Do you mean the log window should be live, continuously updating as the contents of the log file changes?

**Comment by mr-c** [comment]
@kaushik-work Yes, but configurable with a button, as shown in the mock-up image

**Comment by kaushik-work** [comment]
@mr-c so there is a benefit to not having it reload? Why not just have it live stream the log? Thanks.

**Comment by mr-c** [comment]
1. Always stream the latest at the end
2. But allow users to pause the scrolling and to scroll backwards so they can study prior output without it scrolling away.

**Comment by kaushik-work** [comment]
Closed by 2cbedfaaf43b4a88ee97ed5c896717376c090ab3
