### ISSUE TITLE
Is there anyway this can be run as a browser application?

### ISSUE THREAD

**Issue by samyuktr** [rabix/composer#445]

**Comment by kaushik-work** [comment]
Thank you for your interest. Not directly, though, since this is an Electron based application, this can be done with some work.

**Comment by panthar1** [comment]
Hi,

We are just getting started on workflows/pipelines, and while I really like the looks of this project, I am sad to see it will not work in the browser by default.

Are you by chance aware of any other projects that might be better for a browser-based implementation with CWL? I have came across the pipline-builder project, but that creates WDL, not CWL.

**Comment by kaushik-work** [comment]
Hi @panthar1 can you expand a bit on your use case. Like why you want to run this from a browser? Thanks! -Kaushik

**Comment by Bessonov** [comment]
> Hi @panthar1 can you expand a bit on your use case. Like why you want to run this from a browser? Thanks! -Kaushik

@kaushik-work well, to use it as a web based workflow editor for CWL.

**Comment by mmm2006** [comment]
@kaushik-work, How can i run your composer from a browser? It still is an issue for me now. thanks.
