### ISSUE TITLE
Invalid usage of PlatformEntry interface 

### ISSUE THREAD

**Issue by sjaenick** [rabix/composer#458]
https://github.com/rabix/composer/blob/master/src/app/auth/model/auth-credentials.ts#L16
uses a `devTokenURL` in two locations which is not part of the `PlatformEntry` interface.

```
ERROR in src/app/auth/model/auth-credentials.ts(30,13): error TS2322: Type '{ "https://api.sbgenomics.com": { "name": string; "shortName": string; "platformURL": string; }; ...' is not assignable to type '{ [key: string]: PlatformEntry; }'.
  Property '"https://api.sb.biodatacatalyst.nhlbi.nih.gov"' is incompatible with index signature.
    Type '{ "name": string; "shortName": string; "devTokenURL": string; }' is not assignable to type 'PlatformEntry'.
      Object literal may only specify known properties, and '"devTokenURL"' does not exist in type 'PlatformEntry'.

```

**Comment by maekhaus** [comment]
I ran into this same error while running "yarn run build" on a Windows 10 machine.

**Comment by kaushik-work** [comment]
@sjaenick @maekhaus so sorry for this oversight. I have a request, could you check out the 1.5-rc1 branch and see if this works now? The automated tests pass now. Thank you. After a few more tweaks we will release 1.5-rc1 to master and make builds. Best. -Kaushik

**Comment by kaushik-work** [comment]
@sjaenick , @maekhaus I've merged this into master. Please check if you have time. Thank you again for reporting the issue.
