### ISSUE TITLE
Takes too long to execute loops possible error message in latest 1.5.0-rc1 version

### ISSUE THREAD

**Issue by boyangzhao** [rabix/composer#472]
In the latest version 1.5.0-rc1, a lot of my cwl files now when opened in rabix shows the error messages (e.g. Error: Takes too long to execute, loops possible on document.inputs[0].inputBinding.valueFrom) in the Value Transform field. There were no errors like these in previous version.

The value transformation can be for example, $(inputs.alleles.join(",")), but now there is a error message associated with all these.

**Comment by kaushik-work** [comment]
Hi @boyangzhao thank you for reporting this. Could you post an example CWL please if possible.

**Comment by boyangzhao** [comment]
Attached is an example. Thanks!
[collect_rnaseq_metrics.cwl.zip](https://github.com/rabix/composer/files/5252763/collect_rnaseq_metrics.cwl.zip)

**Comment by kaushik-work** [comment]
@gungorbudak let's look at this together when we can. From @boyangzhao 's report this would be a regression. Could this be related to our bumping the `cwl-ts` version (which would indicate a `cwl-ts` bug)?

**Comment by gungorbudak** [comment]
@kaushik-work I downgraded `cwl-ts` to its previous version we used and the error disappeared. Seems to be a `cwl-ts` bug.

**Comment by marijanlekic** [comment]
Its not cwl-ts bug, its related to a bad synchronisation between angular code (not merged well) and latest cwlts

**Comment by kaushik-work** [comment]
Thanks @marijanlekic ! Let's discuss this on our sync today. Thanks for taking a look!

**Comment by kaushik-work** [comment]
Latest `cwl-ts` is incompatible with current Desktop Composer code base. A branch from the last compatible version will be made with the few lines of fixes required to address #465 and will be pushed as a patch version to `npm`. This version will be used in Composer 1.5

**Comment by kaushik-work** [comment]
@boyangzhao the latest release candidate (1.5.0-rc.2) fixes this problem.

**Comment by boyangzhao** [comment]
awesome, thanks!!

**Comment by kaushik-work** [comment]
Closed by ddaa14fa94db5bf7562ebb1612916ec02c2fe200
