### ISSUE TITLE
All `valueFrom` fields on steps get lost

### ISSUE THREAD

**Issue by StarvingMarvin** [rabix/composer#83]
Steps to reproduce:
1. open [bcbio pipeline](https://github.com/bcbio/test_bcbio_cwl/blob/master/run_info-cwl-workflow/main-run_info-cwl.cwl)
2. open code view
3. search for `valueFrom`

**Comment by mayacoda** [comment]
Fixed by https://github.com/rabix/cwl-ts/pull/50
