### ISSUE TITLE
Input port gets connected only at saving time

### ISSUE THREAD

**Issue by mattions** [rabix/composer#85]
I have a CWL 1.0 workflow, which you can get it here: https://github.com/sbg/dna2protein/blob/0027383a9d272c5f0ada348e7866327c50da17a5/dna2protein.cwl

When I try to expose the `transcribe_verbose` input in the workflow editor, a new "input" port is created, but it is detached from everything and I can't connect it with anything else.

![rabix-editor-exposed-port-not-connected](https://cloud.githubusercontent.com/assets/96245/24958802/84fd6154-1f88-11e7-8872-8fa8bf512040.png)

Only when I click Save the connection between the input node and the input port on the the tool node gets created.

**Comment by ivanbatic** [comment]
Not an issue on master anymore, fixed probably a long time ago.
